package entities;

import java.io.Serializable;

public enum ClientRequestType implements Serializable {
	GET_RESERVATIONS,
    UPDATE_ORDER,              // אם עדיין רלוונטי
    GET_RESERVATION_INFO,
    DELETE_RESERVATION,
    REP_LOGIN,
    REGISTER_SUBSCRIBER,
    SUBSCRIBER_LOGIN,

    GET_ACTIVE_RESERVATIONS,
    GET_WAITLIST,
    GET_CURRENT_DINERS,
    GET_SUBSCRIBERS,
    GET_AVAILABLE_SLOTS,
    CREATE_RESERVATION,
    JOIN_WAITLIST,
    LEAVE_WAITLIST,
    PAY_BILL,
    GET_WAITLIST_BY_MONTH,
    MANAGER_TIME_REPORT_BY_MONTH,
    MANAGER_MEMBERS_REPORT_BY_MONTH,
    GET_TABLES,
    ADD_TABLE,
    UPDATE_TABLE_SEATS,
    DEACTIVATE_TABLE,
    ACTIVATE_TABLE,

    GET_OPENING_WEEKLY,
    UPDATE_OPENING_WEEKLY,
    GET_ALL_RESERVATIONS_FOR_SUBSCRIBER,//added by maayan 10.1.26
    GET_DONE_RESERVATIONS_FOR_SUBSCRIBER,//Added by maayan 10.1.26
    GET_SUBSCRIBER_PERSONAL_DETAILS,//Added by maayan 10.1.26
    UPDATE_SUBSCRIBER_PERSONAL_DETAILS,//Added by maayan 10.1.26


    GET_OPENING_SPECIAL,
    UPSERT_OPENING_SPECIAL,
    DELETE_OPENING_SPECIAL
}
