package entities;

import java.io.Serializable;

public enum ServerResponseType implements Serializable {
    ORDERS_LIST,
    UPDATE_SUCCESS,
    UPDATE_FAILED,
    ERROR,
    RESERVATION_FOUND,
    RESERVATION_NOT_FOUND,
    LOGIN_FAILED,
    LOGIN_SUCCESS,
    SUBSCRIBER_LOGIN_SUCCESS,
    SUBSCRIBER_LOGIN_FAILED,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    DELETE_SUCCESS,
    DELETE_FAILED,
    ACTIVE_ORDERS_LIST,
    WAITLIST_LIST,
    CURRENT_DINERS_LIST,
    SUBSCRIBERS_LIST,
    RESERVATIONS_LIST,
    SLOTS_LIST,
    CREATE_FAILED,
    CREATE_SUCCESS,
    WAITLIST_FAILED,
    WAITLIST_SUCCESS,
    PAY_FAILED,
    PAY_SUCCESS
}